// Generated by https://quicktype.io

import { Rol, ShortEmpleado } from "./empelado-interfaces";

export interface PaginationAsignacion {
  data:       Asignacion[] | null;
  pageNumber: number;
  pageSize:   number;
  totalPages: number | null;
  prevPage:   number | null;
  nextPage:   number | null;
}

export interface Asignacion {
  id_asignacion: string;
  creado_el:     string;
  empleado:      ShortEmpleado;
  rol:           Rol;
  message?: string
}

export interface ShortAsignacion {
  id_asignacion: string
  rol: Rol
}

export interface AsignacionForm {
  id_rol: string
  id_empleado: string
}

